import { Component, Input } from "@angular/core";

@Component({
  selector: "app-menu",
  templateUrl: "./menu.component.html",
  styleUrls: ["./menu.component.scss"],
})
export class MenuComponent {
  buttonList: string[] = [
    "All",
    "News",
    "Podcasts",
    "Music",
    "Live",
    "Strategies",
    "Mixes",
    "Rajya Sabha",
    "Wickets",
    "Satsang",
    "Industry",
    "Movie musicals",
    "Thoughts",
    "History",
    "Presentations",
    "Soundtracks",
    "Recently uploaded",
    "Watched",
    "New to you",
    "All",
    "News",
    "Podcasts",
    "Music",
    "Live",
    "Strategies",
    "Mixes",
    "Rajya Sabha",
    "Wickets",
    "Satsang",
    "Industry",
    "Movie musicals",
    "Thoughts",
    "History",
    "Presentations",
    "Soundtracks",
    "Recently uploaded",
    "Watched",
    "New to you",
  ];
}
